#!/usr/bin/env php
<?php
pinba_timer_start(['gegi' => 'local']);
pinba_server_name_set('gegi-pinba-console');
//ini_set('display_errors', 'on');
require __DIR__ . '/src/init.php';

//$app['debug'] = true;

$console = new Pinboard\Console\Application('Intaro Pinboard');
$console->setSilex($app);

$console->add(new Pinboard\Command\InitCommand());
$console->add(new Pinboard\Command\AggregateCommand());
$console->add(new Pinboard\Command\AddUserCommand());

$app->register(
    new \Kurl\Silex\Provider\DoctrineMigrationsProvider($console),
    array(
        'migrations.directory'  => __DIR__ . '/src/Pinboard/DoctrineMigrations',
        'migrations.namespace'  => 'Pinboard\\DoctrineMigrations',
    )
);

$app->boot();
$console->run();
pinba_timer_stop();
