web:
  image: nginx:latest
  ports:
    - "8082:80"
  volumes:
    - ./pinboard/:/code
    - ./site.conf:/etc/nginx/conf.d/site.conf
  links:
    - php
php:
  image: gegi/pinboard:0.0.1
  volumes:
    - ./pinboard/:/code